name: Extensions Compatibility Tests 2.8
on:
  schedule:
    - cron: "0 0 * * *" # runs at midnight every day
  # TODO: DELETE THIS!!!! JUST FOR TESTING PURPOSES!
  pull_request:
    branches:
      - release-2.8

env:
  TEST_USERNAME: admin
  TEST_PASSWORD: password
  CATTLE_BOOTSTRAP_PASSWORD: password
  TEST_BASE_URL: https://127.0.0.1:8005
  API: https://127.0.0.1
  TEST_PROJECT_ID: rancher-dashboard
  CYPRESS_API_URL: http://139.59.134.103:1234/
  TEST_RUN_ID: ${{github.run_number}}-${{github.run_attempt}}-extensions-compatibility-tests
  # Build the dashboard to use in tests. When set to false it will grab `latest` from CDN (useful for running e2e tests quickly)
  BUILD_DASHBOARD: true

  # E2E_BUILD_DIST_NAME: dist
  # E2E_BUILD_DIST_DIR: dist
  # E2E_BUILD_DIST_EMBER_NAME: dist_ember
  # E2E_BUILD_DIST_EMBER_DIR: dist_ember

jobs:
  # e2e-ui-build:
  #   if: "!contains( github.event.pull_request.labels.*.name, 'ci/skip-e2e')"
  #   runs-on: ubuntu-latest
  #   steps:
  #    - uses: actions/checkout@v3
  #      with:
  #       fetch-depth: 1
  #       ref: release-2.8
  #    - name: Setup env
  #      uses: ./.github/actions/setup
  #    - name: Build e2e
  #      run: yarn e2e:build
  #    - name: Upload e2e build
  #      uses: actions/upload-artifact@v4
  #      with:
  #       name: ${{ env.E2E_BUILD_DIST_NAME }}
  #       path: ${{ env.E2E_BUILD_DIST_DIR }}/
  #       if-no-files-found: error
  #       retention-days: 10
  #       compression-level: 9
  #    - name: Upload e2e build ember
  #      uses: actions/upload-artifact@v4
  #      with:
  #       name: ${{ env.E2E_BUILD_DIST_EMBER_NAME }}
  #       path: ${{ env.E2E_BUILD_DIST_EMBER_DIR }}/
  #       if-no-files-found: error
  #       retention-days: 10
  #       compression-level: 9
  e2e-test-extensions-compatibility:
    # if: "!contains( github.event.pull_request.labels.*.name, 'ci/skip-e2e')"
    # needs: e2e-ui-build
    strategy:
      fail-fast: false
      matrix:
        role: [
          { username: 'admin', tag: '@adminUser' }
        ]
        features:  [
          ['@elemental'],
          # ['@kubewarden'],
          # ['@neuvector']
        ]
        rancherEnv: [
          ['v2.8-head', 'release-2.8']
        ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # ref: ${{ matrix.rancherEnv[1] }} TODO: should be removed after it get's merged
          fetch-depth: 1
      - name: Setup env
        uses: ./.github/actions/setup
      
      - name: Download e2e build
        uses:  actions/download-artifact@v4
        with:
         name: ${{ env.E2E_BUILD_DIST_NAME }}
         path: ${{ env.E2E_BUILD_DIST_DIR }}
      - name: Download e2e build ember
        uses:  actions/download-artifact@v4
        with:
         name: ${{ env.E2E_BUILD_DIST_EMBER_NAME }}
         path: ${{ env.E2E_BUILD_DIST_EMBER_DIR }}
      
      # this is where docker is set up with the enviroment
      - name: Run Rancher ${{ matrix.rancherEnv[0] }} - branch:${{ matrix.rancherEnv[1] }}
        run: echo "something 2.8" && export RANCHER_VERSION_E2E=${{ matrix.rancherEnv[0] }} && yarn e2e:docker
      
      ## this is just setting up rancher and user
      - name: Setup Rancher and user
        run: |
          echo "something 2.8 user setup" && yarn e2e:prod
        env: 
          GREP_TAGS: ${{ matrix.role.tag }}Setup+${{ matrix.features[0] }} --@jenkins ${{ matrix.role.tag }}Setup+${{ matrix.features[1] || matrix.features[0] }} --@jenkins
          TEST_USERNAME: ${{ matrix.role.username }}
          TEST_ONLY: setup

      # This is the actual triggering of the e2e test specs
      - name: Run user tests
        run: |
          echo "something 2.8 actual tests" && export SPEC_FILE="cypress/e2e/tests/pages/extensions-compatibility-tests/elemental.spec.ts" && yarn e2e:prod
          [ "$BUILD_DASHBOARD" != "false" ] || exit 0
        env: 
          TEST_SKIP: setup
          GREP_TAGS: ${{ matrix.role.tag }}+${{ matrix.features[0] }} --@jenkins ${{ matrix.role.tag }}+${{ matrix.features[1] || matrix.features[0] }} --@jenkins
          TEST_USERNAME: ${{ matrix.role.username }}
          
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: ${{github.run_number}}-${{github.run_attempt}}-extensions-compatibility-tests-screenshots-${{ matrix.role.tag }}+${{ matrix.features[0] }}
          path: cypress/screenshots